# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://jasonbarbour.com
baseurl: 
title: Jason Barbour
author: Jason
description: Personal page of Jason Barbour
avatar: profile.png
email: jason.barbour@eriasventures.com
github: 
twitter: jtbarbour
linkedin: jasonbarbour
# stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
# disqus: username
google_analytics: UA-43668562-1


# needed for travis-ci build
exclude: [vendor]
